"""TB Created

Revision ID: 05f4ca153cda
Revises: 4b77c3c5d63e
Create Date: 2020-05-31 22:37:07.744780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f4ca153cda'
down_revision = '4b77c3c5d63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nusnetid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_nusnetid'), 'users', ['nusnetid'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.drop_index(op.f('ix_users_nusnetid'), table_name='users')
    op.drop_column('users', 'nusnetid')
    # ### end Alembic commands ###
